config/routes.rb
Rails.application.routes.draw do

  resources :social_networks

  resources :ribbons

  get 'home_website_config' => 'home_website_configs#index', :as => 'home_website_config'
  get 'home_website_config/edit' => 'home_website_configs#edit', :as => 'edit_home_website_config'
  put 'home_website_config/edit' => 'home_website_configs#update'

  get 'general_information' => 'general_information#index', :as => 'general_information'
  get 'general_information/edit' => 'general_information#edit', :as => 'edit_general_information'
  put 'general_information/edit' => 'general_information#update'

  get 'contact_info' => 'contact_infos#index', :as => 'contact_info'
  get 'contact_info/edit' => 'contact_infos#edit', :as => 'edit_contact_info'
  put 'contact_info/edit' => 'contact_infos#update'
  post 'contact_info/edit' => 'contact_infos#update'

  resources :ourworks

  resources :opinions

  resources :member_teams

  get 'home/landing'

  root 'home#landing'

  resources :product_types do
    resources :product_categories
    resources :product_sub_types
    resources :products do
      resources :product_pictures
    end
  end

  get 'signup'  => 'users#new'

  get 'login'  => 'sessions#new'

  post 'login' => 'sessions#create'

  delete 'logout' => 'sessions#destroy'

  resources :users

  get '/preview' => 'website/site#home', as: 'preview'

  get '/preview/product_type/:id' => 'website/site#product_type', as: 'preview_product_type'

  get '/preview/product_types' => 'website/site#product_type_index', as: 'preview_product_type_index'
  get '/preview/product_types/:product_type_id/products' => 'website/site#products_index', as: 'preview_products_index'
  get '/preview/product_types/:product_type_id/products/:id' => 'website/site#product_show', as: 'preview_product_show'
  get '/info/products/:id' => 'website/site#product_show', as: 'preview_product_info'
  get '/info/ourworks' => 'website/site#ourworks_index', as: 'preview_ourworks_index'

end

app/models/contact_info.rb
class ContactInfo < ActiveRecord::Base

  belongs_to :picture

end

app/models/member_team.rb
class MemberTeam < ActiveRecord::Base

  belongs_to :picture

end

app/models/opinion.rb
class Opinion < ActiveRecord::Base
end

app/models/ourwork.rb
class Ourwork < ActiveRecord::Base
  belongs_to :picture
end

app/models/picture.rb
class Picture < ActiveRecord::Base
  mount_uploader :photo, PictureUploader
end

app/models/product.rb
class Product < ActiveRecord::Base

  belongs_to :picture

  belongs_to :product_type

  validates :name, :uniqueness =>  true, :presence => true

end

app/models/product_category.rb
class ProductCategory < ActiveRecord::Base
  belongs_to :product_type
  has_many :product_category_product_sub_types, :dependent => :delete_all
end

app/models/product_picture.rb
class ProductPicture < ActiveRecord::Base

  belongs_to :picture

  belongs_to :product

end

app/models/product_sub_type.rb
class ProductSubType < ActiveRecord::Base
  belongs_to :product_type
  has_many :product_category_product_sub_types, :dependent => :delete_all
  validates :name, :uniqueness =>  true, :presence => true
end

app/models/product_type.rb
class ProductType < ActiveRecord::Base

  belongs_to :picture

  validates :name, presence: true
  validates :order, :uniqueness =>  true, :presence => true

end

app/models/ribbon.rb
class Ribbon < ActiveRecord::Base
  belongs_to :picture
end

app/models/social_network.rb
class SocialNetwork < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base

  has_secure_password

  validates :first_name, :uniqueness =>  false, :presence => true

  validates :user_name, :uniqueness =>  true, :presence => true

  validates :last_name, :uniqueness =>  false, :presence => true

end

app/controllers/product_types_controller.rb
class ProductTypesController < SecurityController
  before_action :set_product_type, only: [:show, :edit, :update, :destroy]

  # GET /product_types
  # GET /product_types.json
  def index
    @product_types = ProductType.all
  end

  # GET /product_types/1
  # GET /product_types/1.json
  def show

    query_by_name = params[:q].to_s

    @products =

    if query_by_name.size > 0

      @products = Product
                      .where(product_type_id: @product_type.id)
                      .where('lower(name) LIKE ?' , "%#{query_by_name.downcase}%")
                      .order(:name)
                      .paginate(:page => params[:page], :per_page => 10)

    else

      @products = Product
          .where(product_type_id: @product_type.id)
          .order(:name)
          .paginate(:page => params[:page], :per_page => 10)

    end

  end

  # GET /product_types/new
  def new
    @product_type = ProductType.new
  end

  # GET /product_types/1/edit
  def edit
  end

  # POST /product_types
  # POST /product_types.json
  def create
    @product_type = ProductType.new(product_type_params)

    p = Picture.new(photo: params[:product_type][:image])

    p.save!

    @product_type.picture = p

    respond_to do |format|
      if @product_type.save
        format.html { redirect_to @product_type, notice:'El tipo de producto ha sido creado correctamente.' }
        format.json { render :show, status: :created, location: @product_type }
      else
        format.html { render :new }
        format.json { render json: @product_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /product_types/1
  # PATCH/PUT /product_types/1.json
  def update

    unless params[:product_type][:image].nil?


      unless @product_type.picture.nil?

        @product_type.picture.remove_photo!

        @product_type.picture.save!

        @product_type.picture.update(photo: params[:product_type][:image])

        @product_type.picture.save!

      else

        p = Picture.new(photo: params[:product_type][:image])

        p.save!

        @product_type.picture = p

      end


    end

    respond_to do |format|
      if @product_type.update(product_type_params)
        format.html { redirect_to product_types_path, notice: 'El tipo de producto ha sido editado correctamente.' }
        format.json { render :show, status: :ok, location: @product_type }
      else
        format.html { render :edit }
        format.json { render json: @product_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /product_types/1
  # DELETE /product_types/1.json
  def destroy

    products = Product.where(product_type_id: @product_type.id)

    products.each do |product|

      p = @product.picture

      p.remove_photo!

      product.destroy

      p.destroy!

    end

    p = @product_type.picture

    p.remove_photo!

    p.destroy!

    @product_type.destroy

    respond_to do |format|
      format.html { redirect_to product_types_url, notice: 'El tipo de producto ha sido eliminado correctamente.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product_type
      @product_type = ProductType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_type_params
      params.require(:product_type).permit(:name, :have_classification, :have_sub_type, :order, :allow_category)
    end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/opinions_helper.rb
module OpinionsHelper
end

app/helpers/ourworks_helper.rb
module OurworksHelper
end

app/helpers/product_types_helper.rb
module ProductTypesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/ribbons_helper.rb
module RibbonsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/product_types/_form.html.erb
<%= form_for(@product_type, html: {novalidate:'novalidate', class: 'form_validation'}) do |f| %>

    <% if @product_type.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@product_type.errors.count, "error") %> prohibited this product_type from being saved:</h2>

          <ul>
            <% @product_type.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="row clearfix">
      <div class="col-sm-12">
        <div class="form-group">
          <div class="form-line">
            <%= f.text_field :name,
                             class: 'form-control',
                             placeholder: 'Nombre',
                             required: '',
                             :'aria-required'=>'true',
                             :'aria-invalid'=>'true',
                             maxlength:'100',
                             minlength:'5'
            %>
          </div>
        </div>
      </div>
    </div>

    <div class="row clearfix">
      <div class="col-sm-12">
        <div class="form-group">
          <div class="form-line">
            <%= f.number_field :order,
                               class: 'form-control',
                               placeholder: 'Orden',
                               required: 'required',
                               :'aria-required'=>'true',
                               min: 0,
                               step: 1
            %>
          </div>
        </div>
      </div>
    </div>

    <div class="row clearfix">
      <div class="col-sm-12">
        <div class="form-group">
          <%= f.check_box :have_sub_type%>
          <label for="product_type_have_sub_type">Subdividir en sub tipos</label>
        </div>
      </div>
    </div>

    <div class="row clearfix">
      <div class="col-sm-12">
        <div class="form-group">
          <%= f.check_box :have_classification%>
          <label for="product_type_have_classification">Subdividir en Clasificaciones</label>
        </div>
      </div>
    </div>

    <div class="row clearfix">
      <div class="col-sm-12">
        <div class="form-group">
          <%= f.check_box :allow_category%>
          <label for="product_type_allow_category">Subdividir en Categorias los Productos</label>
        </div>
      </div>
    </div>

    <div class="row clearfix">
      <div class="col-sm-12">
        <div class="form-group">

          <% unless @product_type.picture.nil?  %>
              <%= image_tag @product_type.picture.photo_url, style: 'width: 100%; max-width: 300px; height: auto;' %>
          <% end %>
          <div class="form-line input-group">

            <%= f.file_field :image, class:'file', style:'display:none' %>

            <span class="input-group-btn">
                    <button class="browse btn btn-primary" type="button">
                      <i class="material-icons">insert_photo</i>
                    </button>
                </span>
            <input type="text" class="form-control" disabled placeholder="Seleccione un imágen" value="<%= (@product_type.picture.nil? ? '' : @product_type.picture.photo_identifier ) %>">
          </div>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-xs-6 col-sm-4">
        <button type="submit" class="btn btn-primary m-t-15 waves-effect btn-block teal">Guardar</button>
      </div>
      <div class="col-xs-6 col-sm-4">
        <%= link_to 'Atrás', product_types_path, class: 'btn btn-default m-t-15 waves-effect btn-block' %>
      </div>
    </div>
<% end %>

app/views/product_types/edit.html.erb
<div class="block-header">
  <ol class="breadcrumb breadcrumb-col-teal">
    <li>
      <a href="/">
        <i class="material-icons">home</i>
      </a>
    </li>
    <li>
      <%= link_to 'Tipo de Productos', product_types_path %>
    </li>
    <li class="active">Editar</li>
  </ol>
  <h1>
    Tipo de Producto
  </h1>
</div>
<!-- Input -->
<div class="row clearfix">
  <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
    <div class="card">
      <div class="header">
        <h2>
          Editar Tipo de Producto
        </h2>
      </div>
      <div class="body">
        <%= render 'form' %>
      </div>
    </div>
  </div>
</div>

app/views/product_types/index.html.erb
<div class="block-header">
  <ol class="breadcrumb breadcrumb-col-teal">
    <li>
      <a href="/">
        <i class="material-icons">home</i>
      </a>
    </li>
    <li class="active">Tipo de Productos</li>
  </ol>
  <h1>
    Tipos de Producto
  </h1>
</div>
<div class="row clearfix">
  <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
    <div class="card">
      <div class="body table-responsive">
        <% if @product_types.size > 0 %>
            <table class="table table-striped">
              <thead>
              <tr>
                <th>Nombre</th>
                <th style="width: 360px;"></th>
              </tr>
              </thead>

              <tbody>
              <% @product_types.each do |product_type| %>
                  <tr>
                    <td>
                      <% unless product_type.picture.nil? %>
                          <%= image_tag product_type.picture.photo_url, width: '36px', height: '36px' %>
                      <% end %>
                      <%= product_type.name %>
                    </td>
                    <td>
                      <%= link_to preview_product_type_path(product_type.id), target: '_blank', class: 'btn btn-default',
                                  'data-toggle'=> 'tooltip', 'data-placement'=> 'top', 'title'=> 'Vista Previa'  do %>
                          <i class="material-icons">public</i>
                      <% end %>
                      <%= link_to product_type_product_categories_path(product_type.id),
                                  class: 'btn btn-default', 'data-toggle'=> 'tooltip',
                                  'data-placement'=> 'top', 'title'=> 'Categoria de Producto' do %>
                          <i class="material-icons">dns</i>
                      <% end %>
                      <%= link_to product_type_product_sub_types_path(product_type.id),
                                  class: 'btn btn-default', 'data-toggle'=> 'tooltip',
                                  'data-placement'=> 'top', 'title'=> 'Sub Tipos de Producto' do %>
                          <i class="material-icons">local_offer</i>
                      <% end %>
                      <%= link_to product_type, class: 'btn btn-default', 'data-toggle'=> 'tooltip',
                                  'data-placement'=> 'top', 'title'=> 'Ver Productos'  do %>
                          <i class="material-icons">list</i>
                      <% end %>
                      <%= link_to edit_product_type_path(product_type), class: 'btn btn-default', 'data-toggle'=> 'tooltip',
                                  'data-placement'=> 'top', 'title'=> 'Editar Tipo de Producto'   do %>
                          <i class="material-icons">create</i>
                      <% end %>
                      <%= link_to product_type, method: :delete, data: { confirm: 'Are you sure?' },
                                  class: 'btn btn-danger', 'data-toggle'=> 'tooltip',
                                  'data-placement'=> 'top', 'title'=> 'Eliminar Tipo de Producto'   do %>
                          <i class="material-icons">delete</i>
                      <% end %>
                    </td>
                  </tr>
              <% end %>
              </tbody>
            </table>
        <% else %>
            <div class="alert alert-info margin-0 text-center">
              No existe ningún tipo de producto cargado en el sistema
            </div>
        <% end %>
      </div>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-xs-12 col-sm-3">
    <%= link_to 'Nuevo Tipo de Producto', new_product_type_path, class:'btn btn-primary waves-effect btn-block teal' %>
  </div>
</div>

app/views/product_types/new.html.erb
<div class="block-header">
  <ol class="breadcrumb breadcrumb-col-teal">
    <li>
      <a href="/">
        <i class="material-icons">home</i>
      </a>
    </li>
    <li>
      <%= link_to 'Tipo de Productos', product_types_path %>
    </li>
    <li class="active">Crear</li>
  </ol>
  <h1>
    Tipo de Producto
  </h1>
</div>
<!-- Input -->
<div class="row clearfix">
  <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
    <div class="card">
      <div class="header">
        <h2>Crear Tipo de Producto</h2>
      </div>
      <div class="body">
        <%= render 'form' %>
      </div>
    </div>
  </div>
</div>

app/views/product_types/show.html.erb
<div class="block-header">
  <ol class="breadcrumb breadcrumb-col-teal">
    <li>
      <a href="/">
        <i class="material-icons">home</i>
      </a>
    </li>
    <li>
      <%= link_to 'Tipo de Productos', product_types_path %>
    </li>
    <li class="active">Ver</li>
  </ol>
  <h1>
    <%= @product_type.name %>
  </h1>
</div>

<div class="row clearfix">
  <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
    <div class="card">
      <div class="header">
        <h2>Productos</h2>
      </div>

      <form novalidate="novalidate" class="form_validation">

        <div class="row clearfix center" style="margin: 20px 20px 0;">
          <div class="col-xs-12">
            <div class="form-group">
              <div class="input-group">
                <div class="form-line">
                  <input class="form-control" placeholder="Buscar"  size="100" type="text" name="q" value="<%= params[:q].to_s %>">
                </div>
                <div class="input-group-addon">
                  <button type="submit" class="btn btn-primary">
                    <i class="material-icons" style="color: white !important;">search</i>
                  </button>
                </div>
              </div>
            </div>
          </div>
        </div>
      </form>

      <div class="body table-responsive">
        <% if @products.size > 0 %>
            <table class="table table-striped">
              <thead>
              <tr>
                <th>Nombre</th>
                <th>Precio</th>
                <th>Habilitado</th>
                <th style="width: 180px;"></th>
              </tr>
              </thead>
              <tbody>
              <% @products.each do |product| %>
                  <tr>
                    <td>
                      <% unless product.picture_id.nil? %>
                          <%= image_tag product.picture.photo_url, width: '36px', height: '36px' %>
                      <% end %>
                      <%= product.name %>
                    </td>
                    <td>$ <%= number_with_precision(product.price, precision: 2) %></td>
                    <td><%= product.enabled ? 'Si' : 'No' %></td>
                    <td>
                      <%= link_to product_type_product_product_pictures_path(@product_type,product), class: 'btn btn-default'  do %>
                          <i class="material-icons">photo_library</i>
                      <% end %>
                      <%= link_to edit_product_type_product_path(@product_type,product), class: 'btn btn-default'  do %>
                          <i class="material-icons">create</i>
                      <% end %>
                      <%= link_to [@product_type,product], method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger'  do %>
                          <i class="material-icons">delete</i>
                      <% end %>
                    </td>
                  </tr>
              <% end %>
              </tbody>
            </table>
            <div class="pagination_container">
              <%= will_paginate @products, renderer: BootstrapPagination::Rails %>
            </div>
        <% else %>
            <div class="alert alert-info margin-0 text-center">
              No existe ningún producto cargado en el sistema para el tipo de producto seleccionado
            </div>
        <% end %>
        <div class="row">
          <div class="col-xs-6 col-sm-4">
            <%= link_to 'Atrás', product_types_path, class: 'btn btn-default m-t-15 waves-effect btn-block' %>
          </div>
          <div class="col-xs-6 col-sm-4">
            <%= link_to 'Nuevo Producto', new_product_type_product_path( @product_type), class: 'btn btn-primary m-t-15 waves-effect btn-block' %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>