config/routes.rb
Rails.application.routes.draw do

  resources :social_networks

  resources :ribbons

  get 'home_website_config' => 'home_website_configs#index', :as => 'home_website_config'
  get 'home_website_config/edit' => 'home_website_configs#edit', :as => 'edit_home_website_config'
  put 'home_website_config/edit' => 'home_website_configs#update'

  get 'general_information' => 'general_information#index', :as => 'general_information'
  get 'general_information/edit' => 'general_information#edit', :as => 'edit_general_information'
  put 'general_information/edit' => 'general_information#update'

  get 'contact_info' => 'contact_infos#index', :as => 'contact_info'
  get 'contact_info/edit' => 'contact_infos#edit', :as => 'edit_contact_info'
  put 'contact_info/edit' => 'contact_infos#update'
  post 'contact_info/edit' => 'contact_infos#update'

  resources :ourworks

  resources :opinions

  resources :member_teams

  get 'home/landing'

  root 'home#landing'

  resources :product_types do
    resources :product_categories
    resources :product_sub_types
    resources :products do
      resources :product_pictures
    end
  end

  get 'signup'  => 'users#new'

  get 'login'  => 'sessions#new'

  post 'login' => 'sessions#create'

  delete 'logout' => 'sessions#destroy'

  resources :users

  get '/preview' => 'website/site#home', as: 'preview'

  get '/preview/product_type/:id' => 'website/site#product_type', as: 'preview_product_type'

  get '/preview/product_types' => 'website/site#product_type_index', as: 'preview_product_type_index'
  get '/preview/product_types/:product_type_id/products' => 'website/site#products_index', as: 'preview_products_index'
  get '/preview/product_types/:product_type_id/products/:id' => 'website/site#product_show', as: 'preview_product_show'
  get '/info/products/:id' => 'website/site#product_show', as: 'preview_product_info'
  get '/info/ourworks' => 'website/site#ourworks_index', as: 'preview_ourworks_index'

end

app/models/contact_info.rb
class ContactInfo < ActiveRecord::Base

  belongs_to :picture

end

app/models/member_team.rb
class MemberTeam < ActiveRecord::Base

  belongs_to :picture

end

app/models/opinion.rb
class Opinion < ActiveRecord::Base
end

app/models/ourwork.rb
class Ourwork < ActiveRecord::Base
  belongs_to :picture
end

app/models/picture.rb
class Picture < ActiveRecord::Base
  mount_uploader :photo, PictureUploader
end

app/models/product.rb
class Product < ActiveRecord::Base

  belongs_to :picture

  belongs_to :product_type

  validates :name, :uniqueness =>  true, :presence => true

end

app/models/product_category.rb
class ProductCategory < ActiveRecord::Base
  belongs_to :product_type
  has_many :product_category_product_sub_types, :dependent => :delete_all
end

app/models/product_picture.rb
class ProductPicture < ActiveRecord::Base

  belongs_to :picture

  belongs_to :product

end

app/models/product_sub_type.rb
class ProductSubType < ActiveRecord::Base
  belongs_to :product_type
  has_many :product_category_product_sub_types, :dependent => :delete_all
  validates :name, :uniqueness =>  true, :presence => true
end

app/models/product_type.rb
class ProductType < ActiveRecord::Base

  belongs_to :picture

  validates :name, presence: true
  validates :order, :uniqueness =>  true, :presence => true

end

app/models/ribbon.rb
class Ribbon < ActiveRecord::Base
  belongs_to :picture
end

app/models/social_network.rb
class SocialNetwork < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base

  has_secure_password

  validates :first_name, :uniqueness =>  false, :presence => true

  validates :user_name, :uniqueness =>  true, :presence => true

  validates :last_name, :uniqueness =>  false, :presence => true

end

app/controllers/product_pictures_controller.rb
class ProductPicturesController < SecurityController
  before_action :set_product_picture, only: [:show, :edit, :update, :destroy]

  before_action :set_product

  # GET /product_pictures
  # GET /product_pictures.json
  def index
    @product_pictures = ProductPicture.where(product: @product)
    @product_picture = ProductPicture.new
  end

  # GET /product_pictures/1
  # GET /product_pictures/1.json
  def show
  end

  # GET /product_pictures/new
  def new
    @product_picture = ProductPicture.new
  end

  # GET /product_pictures/1/edit
  def edit
  end

  # POST /product_pictures
  # POST /product_pictures.json
  def create

    if params[:image]

      @product_picture = ProductPicture.new

      p = Picture.new(photo: params[:image])

      p.save!

      @product_picture.picture = p

      @product_picture.product = @product

      respond_to do |format|
        if @product_picture.save
         # format.html { redirect_to product_type_product_product_pictures_path(@product.product_type, @product), notice: 'Product picture was successfully created.' }
         # format.json { render :show, status: :created, location: [@product.product_type, @product] }
          format.js
        else
          format.html { render :new }
          format.json { render json: @product_picture.errors, status: :unprocessable_entity }
          format.js
        end
      end

    else

      respond_to do |format|
          format.html { redirect_to product_type_product_product_pictures_path(@product.product_type, @product), notice: '' }
          format.json { render :index, status: :created, location: [@product.product_type, @product] }
          format.js
      end

    end

  end

  # PATCH/PUT /product_pictures/1
  # PATCH/PUT /product_pictures/1.json
  def update
    respond_to do |format|
      if @product_picture.update(product_picture_params)
        format.html { redirect_to @product_picture, notice: 'Product picture was successfully updated.' }
        format.json { render :show, status: :ok, location: @product_picture }
      else
        format.html { render :edit }
        format.json { render json: @product_picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /product_pictures/1
  # DELETE /product_pictures/1.json
  def destroy

    p = @product_picture.picture

    p.remove_photo!

    @product_picture.destroy

    p.destroy!

    respond_to do |format|
      format.html { redirect_to product_type_product_product_pictures_path(@product.product_type, @product), notice: 'El la imágen ha sido eliminada correctamente.' }
      format.json { head :no_content }
      format.js
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_product_picture
    @product_picture = ProductPicture.find(params[:id])
  end

  def set_product_type
    @product_type = ProductType.find(params[:product_type_id])
  end

  def set_product
    @product = Product.find(params[:product_id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def product_picture_params
    #params.require(:product_picture).permit(:product_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/opinions_helper.rb
module OpinionsHelper
end

app/helpers/ourworks_helper.rb
module OurworksHelper
end

app/helpers/product_pictures_helper.rb
module ProductPicturesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/ribbons_helper.rb
module RibbonsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/product_pictures/_form.html.erb
<%= form_for([@product.product_type, @product, @product_picture], :remote => true, :html => {multipart: true}) do |f| %>

    <div class="modal-body">

      <%= hidden_field_tag :authenticity_token, form_authenticity_token %>

      <div class="input-file-container">
        <input class="input-file" id="image" type="file" name="image">
        <label tabindex="0" for="image" class="input-file-trigger btn bg-teal">Seleccione una imágen</label>
      </div>
      <p class="file-return"></p>

    </div>
    <div class="modal-footer">

      <button type="button" class="btn btn-link waves-effect" data-dismiss="modal">Cancelar</button>

      <button type="submit" class="btn btn-link waves-effect btn-file-submit" disabled > Subir </button>

    </div>


<% end %>

app/views/product_pictures/create.js.erb
var item = '<div class="col-lg-3 col-md-3 col-sm-4 col-xs-12"> \
              <div class="card product_picture" id="product_picture_<%= @product_picture.id %>"> \
                <a data-confirm="Are you sure?" data-remote="true" rel="nofollow" data-method="delete" href="/product_types/<%= @product_picture.product.product_type.id %>/products/<%= @product_picture.product.id %>/product_pictures/<%= @product_picture.id %>"> \
                  <div class="image" style="background-image: url(\'<%= @product_picture.picture.photo %>\');"></div> \
                  <div class="cover-delete"> \
                    <i class="material-icons">delete</i> \
                  </div> \
                </a> \
              </div> \
            </div>';

$('#pictures').append(item);

$('#modal_form_upload').modal('hide');

$('#modal_form_upload').find('.progress').hide();

$('#modal_form_upload').find('.input-file').val('');

$('#modal_form_upload').find('.file-return').html('');

$(".btn-file-submit").attr('disabled', 'disabled');

app/views/product_pictures/destroy.js.erb
$('#product_picture_<%= @product_picture.id %>').parent().remove();

app/views/product_pictures/edit.html.erb
<h1>Editing Product Picture</h1>

<%= render 'form' %>

<%= link_to 'Show', @product_picture %> |
<%= link_to 'Back', product_pictures_path %>

app/views/product_pictures/index.html.erb
<div class="block-header">
  <ol class="breadcrumb breadcrumb-col-teal">
    <li>
      <a href="/">
        <i class="material-icons">home</i>
      </a>
    </li>
    <li>
      <%= link_to 'Tipo de Productos', product_types_path %>
    </li>
    <li>
      <%= link_to @product.product_type.name, @product.product_type %>
    </li>
    <li>
      <%= link_to @product.name, edit_product_type_product_path(@product.product_type, @product)%>
    </li>
    <li class="active">Editar</li>
  </ol>
  <h1>
    <%= @product.name %> - Imágenes
  </h1>
</div>
<!-- Input -->
<div class="row clearfix">
  <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
    <div class="card">
      <div class="header">
        <h2>Imágenes</h2>
      </div>
      <div class="body">

        <div class="row" id="pictures">
          <% @product_pictures.each do |p| %>
              <div class="col-lg-3 col-md-3 col-sm-4 col-xs-12">
                <div class="card product_picture" id="product_picture_<%= p.id %>">
                  <%= link_to product_type_product_product_picture_path(p.product.product_type, p.product, p), :method => :delete, data: { confirm: 'Are you sure?' }, :remote => true do %>
                    <div class="image" style="background-image: url('<%= p.picture.photo %>');"></div>
                      <div class="cover-delete">
                        <i class="material-icons">delete</i>
                      </div>
                  <% end %>
                </div>
              </div>
          <% end %>
        </div>

      </div>
      <div class="footer">

        <button type="button" class="btn waves-effect m-r-20 btn-block bg-teal btn-lg" data-toggle="modal" data-target="#modal_form_upload">
          Cargar Imagen
        </button>

      </div>
    </div>
  </div>
</div>

<div class="modal fade" id="modal_form_upload" tabindex="-1" role="dialog" style="display: none;">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title" id="defaultModalLabel">Cargar Imágenes</h4>
      </div>
      <%= render 'form' %>

      <div class="progress" style="display: none;">
        <div class="progress-bar bg-teal progress-bar-striped active" role="progressbar"  style="width: 100%;">
          Subiendo imagen
        </div>
      </div>

    </div>
  </div>
</div>

app/views/product_pictures/new.html.erb
<h1>New Product Picture</h1>

<%= render 'form' %>

<%= link_to 'Back', product_pictures_path %>

app/views/product_pictures/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_product_picture_path(@product_picture) %> |
<%= link_to 'Back', product_pictures_path %>