config/routes.rb
Rails.application.routes.draw do

  resources :social_networks

  resources :ribbons

  get 'home_website_config' => 'home_website_configs#index', :as => 'home_website_config'
  get 'home_website_config/edit' => 'home_website_configs#edit', :as => 'edit_home_website_config'
  put 'home_website_config/edit' => 'home_website_configs#update'

  get 'general_information' => 'general_information#index', :as => 'general_information'
  get 'general_information/edit' => 'general_information#edit', :as => 'edit_general_information'
  put 'general_information/edit' => 'general_information#update'

  get 'contact_info' => 'contact_infos#index', :as => 'contact_info'
  get 'contact_info/edit' => 'contact_infos#edit', :as => 'edit_contact_info'
  put 'contact_info/edit' => 'contact_infos#update'
  post 'contact_info/edit' => 'contact_infos#update'

  resources :ourworks

  resources :opinions

  resources :member_teams

  get 'home/landing'

  root 'home#landing'

  resources :product_types do
    resources :product_categories
    resources :product_sub_types
    resources :products do
      resources :product_pictures
    end
  end

  get 'signup'  => 'users#new'

  get 'login'  => 'sessions#new'

  post 'login' => 'sessions#create'

  delete 'logout' => 'sessions#destroy'

  resources :users

  get '/preview' => 'website/site#home', as: 'preview'

  get '/preview/product_type/:id' => 'website/site#product_type', as: 'preview_product_type'

  get '/preview/product_types' => 'website/site#product_type_index', as: 'preview_product_type_index'
  get '/preview/product_types/:product_type_id/products' => 'website/site#products_index', as: 'preview_products_index'
  get '/preview/product_types/:product_type_id/products/:id' => 'website/site#product_show', as: 'preview_product_show'
  get '/info/products/:id' => 'website/site#product_show', as: 'preview_product_info'
  get '/info/ourworks' => 'website/site#ourworks_index', as: 'preview_ourworks_index'

end

app/models/contact_info.rb
class ContactInfo < ActiveRecord::Base

  belongs_to :picture

end

app/models/member_team.rb
class MemberTeam < ActiveRecord::Base

  belongs_to :picture

end

app/models/opinion.rb
class Opinion < ActiveRecord::Base
end

app/models/ourwork.rb
class Ourwork < ActiveRecord::Base
  belongs_to :picture
end

app/models/picture.rb
class Picture < ActiveRecord::Base
  mount_uploader :photo, PictureUploader
end

app/models/product.rb
class Product < ActiveRecord::Base

  belongs_to :picture

  belongs_to :product_type

  validates :name, :uniqueness =>  true, :presence => true

end

app/models/product_category.rb
class ProductCategory < ActiveRecord::Base
  belongs_to :product_type
  has_many :product_category_product_sub_types, :dependent => :delete_all
end

app/models/product_picture.rb
class ProductPicture < ActiveRecord::Base

  belongs_to :picture

  belongs_to :product

end

app/models/product_sub_type.rb
class ProductSubType < ActiveRecord::Base
  belongs_to :product_type
  has_many :product_category_product_sub_types, :dependent => :delete_all
  validates :name, :uniqueness =>  true, :presence => true
end

app/models/product_type.rb
class ProductType < ActiveRecord::Base

  belongs_to :picture

  validates :name, presence: true
  validates :order, :uniqueness =>  true, :presence => true

end

app/models/ribbon.rb
class Ribbon < ActiveRecord::Base
  belongs_to :picture
end

app/models/social_network.rb
class SocialNetwork < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base

  has_secure_password

  validates :first_name, :uniqueness =>  false, :presence => true

  validates :user_name, :uniqueness =>  true, :presence => true

  validates :last_name, :uniqueness =>  false, :presence => true

end

app/controllers/product_sub_types_controller.rb
class ProductSubTypesController < SecurityController

  before_action :set_product_sub_type, only: [:show, :edit, :update, :destroy]

  before_action :set_product_type

  # GET /product_sub_types
  # GET /product_sub_types.json
  def index
    @product_sub_types = ProductSubType.where(product_type_id: @product_type.id).order(:name)
  end

  # GET /product_sub_types/1
  # GET /product_sub_types/1.json
  def show
  end

  # GET /product_sub_types/new
  def new
    @product_sub_type = ProductSubType.new
  end

  # GET /product_sub_types/1/edit
  def edit
  end

  # POST /product_sub_types
  # POST /product_sub_types.json
  def create
    @product_sub_type = ProductSubType.new(product_sub_type_params)
    @product_sub_type.product_type_id = @product_type.id
    respond_to do |format|
      if @product_sub_type.save
        format.html { redirect_to product_type_product_sub_types_path(@product_type), notice: 'El sub tipo de producto fue creado correctamente.' }
        format.json { render :show, status: :created, location: @product_sub_type }
      else
        format.html { render :new }
        format.json { render json: @product_sub_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /product_sub_types/1
  # PATCH/PUT /product_sub_types/1.json
  def update
    @product_sub_type.product_type_id = @product_type.id
    respond_to do |format|
      if @product_sub_type.update(product_sub_type_params)
        format.html { redirect_to product_type_product_sub_types_path(@product_type), notice: 'El sub tipo de producto fue editado correctamente.' }
        format.json { render :show, status: :ok, location: @product_sub_type }
      else
        format.html { render :edit }
        format.json { render json: @product_sub_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /product_sub_types/1
  # DELETE /product_sub_types/1.json
  def destroy
    @product_sub_type.destroy
    respond_to do |format|
      format.html { redirect_to product_type_product_sub_types_path(@product_type), notice: 'El sub tipo de producto fue eliminado correctamente.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_product_sub_type
    @product_sub_type = ProductSubType.find(params[:id])
  end

  def set_product_type
    @product_type = ProductType.find(params[:product_type_id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def product_sub_type_params
    params.require(:product_sub_type).permit(:name, :type_product, :order, :denomination)
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/opinions_helper.rb
module OpinionsHelper
end

app/helpers/ourworks_helper.rb
module OurworksHelper
end

app/helpers/product_sub_types_helper.rb
module ProductSubTypesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/ribbons_helper.rb
module RibbonsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/product_sub_types/_form.html.erb
<%= form_for([@product_type,@product_sub_type], html: {novalidate:'novalidate', class: 'form_validation'}) do |f| %>

    <div class="row clearfix">
      <div class="col-sm-12">
        <div class="form-group">
          <div class="form-line">
            <%= f.text_field :name,
                             class: 'form-control',
                             placeholder: 'Nombre',
                             required: '',
                             :'aria-required'=>'true',
                             :'aria-invalid'=>'true',
                             maxlength:'150',
                             minlength:'5'
            %>
          </div>
        </div>
      </div>
    </div>

    <div class="row clearfix">
      <div class="col-sm-12">
        <div class="form-group">
          <div class="form-line">
            <%= f.text_field :denomination,
                             class: 'form-control',
                             placeholder: 'Denominación',
                             required: '',
                             :'aria-required'=>'true',
                             :'aria-invalid'=>'true',
                             maxlength:'150',
                             minlength:'5'
            %>
          </div>
        </div>
      </div>
    </div>

    <div class="row clearfix">
      <div class="col-sm-12">
        <div class="form-group">
          <div class="form-line">
            <%= f.number_field :order,
                               class: 'form-control',
                               placeholder: 'Orden',
                               required: 'required',
                               :'aria-required'=>'true',
                               min: 0,
                               step: 1
            %>
          </div>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-xs-6 col-sm-4">
        <button type="submit" class="btn btn-primary m-t-15 waves-effect btn-block teal">Guardar</button>
      </div>
      <div class="col-xs-6 col-sm-4">
        <%= link_to 'Atrás', product_types_path, class: 'btn btn-default m-t-15 waves-effect btn-block' %>
      </div>
    </div>

<% end %>

app/views/product_sub_types/edit.html.erb
<div class="block-header">
  <ol class="breadcrumb breadcrumb-col-teal">
    <li>
      <a href="/">
        <i class="material-icons">home</i>
      </a>
    </li>
    <li>
      <%= link_to 'Tipo de Productos', product_types_path %>
    </li>
    <li>
      <%= link_to @product_type.name, @product_type %>
    </li>
    <li class="active">Editar</li>
  </ol>
  <h1>
    Sub Tipo de Productos
  </h1>
</div>

<div class="row clearfix">
  <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
    <div class="card">
      <div class="header">
        <h2>Editar Sub Tipo de Producto</h2>
      </div>
      <div class="body">
        <%= render 'form' %>
      </div>
    </div>
  </div>
</div>

app/views/product_sub_types/index.html.erb
<div class="block-header">
  <ol class="breadcrumb breadcrumb-col-teal">
    <li>
      <a href="/">
        <i class="material-icons">home</i>
      </a>
    </li>
    <li>
      <%= link_to 'Tipo de Productos', product_types_path %>
    </li>
    <li class="active">Sub Tipo de Productos</li>
  </ol>
  <h1>
    <%= @product_type.name %>
  </h1>
</div>
<div class="row clearfix">
  <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
    <div class="card">
      <div class="header">
        <h2>Sub Tipos de Producto</h2>
      </div>
      <div class="body table-responsive">
        <% if @product_sub_types.size > 0 %>
            <table class="table table-striped">
              <thead>
              <tr>
                <th>Name</th>
                <th style="width: 120px;"></th>
              </tr>
              </thead>

              <tbody>
              <% @product_sub_types.each do |product_sub_type| %>
                  <tr>
                    <td><%= product_sub_type.name %></td>
                    <td>
                      <%= link_to edit_product_type_product_sub_type_path(@product_type, product_sub_type), class: 'btn btn-default' do %>
                          <i class="material-icons">create</i>
                      <% end %>
                      <%= link_to [@product_type, product_sub_type], method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' do %>
                          <i class="material-icons">delete</i>
                      <% end %>
                    </td>
                  </tr>
              <% end %>
              </tbody>
            </table>

        <% else %>
            <div class="alert alert-info margin-0 text-center">
              No existe ningún sub tipo de producto cargado en el sistema para el tipo de producto seleccionado
            </div>
        <% end %>
        <div class="row">
          <div class="col-xs-6 col-sm-4">
            <%= link_to 'Atrás', product_types_path, class: 'btn btn-default m-t-15 waves-effect btn-block' %>
          </div>
          <div class="col-xs-6 col-sm-4">
            <%= link_to 'Nuevo Sub Tipo', new_product_type_product_sub_type_path( @product_type), class: 'btn btn-primary m-t-15 waves-effect btn-block' %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/product_sub_types/new.html.erb
<div class="block-header">
  <ol class="breadcrumb breadcrumb-col-teal">
    <li>
      <a href="/">
        <i class="material-icons">home</i>
      </a>
    </li>
    <li>
      <%= link_to 'Tipo de Productos', product_types_path %>
    </li>
    <li>
      <%= link_to @product_type.name, @product_type %>
    </li>
    <li class="active">Crear</li>
  </ol>
  <h1>
    Sub Tipo de Productos
  </h1>
</div>

<div class="row clearfix">
  <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
    <div class="card">
      <div class="header">
        <h2>Crear Sub Tipo de Producto</h2>
      </div>
      <div class="body">
        <%= render 'form' %>
      </div>
    </div>
  </div>
</div>

app/views/product_sub_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product_sub_type.name %>
</p>

<p>
  <strong>Type product:</strong>
  <%= @product_sub_type.type_product %>
</p>

<%= link_to 'Edit', edit_product_sub_type_path(@product_sub_type) %> |
<%= link_to 'Back', product_sub_types_path %>