config/routes.rb
Rails.application.routes.draw do

  resources :social_networks

  resources :ribbons

  get 'home_website_config' => 'home_website_configs#index', :as => 'home_website_config'
  get 'home_website_config/edit' => 'home_website_configs#edit', :as => 'edit_home_website_config'
  put 'home_website_config/edit' => 'home_website_configs#update'

  get 'general_information' => 'general_information#index', :as => 'general_information'
  get 'general_information/edit' => 'general_information#edit', :as => 'edit_general_information'
  put 'general_information/edit' => 'general_information#update'

  get 'contact_info' => 'contact_infos#index', :as => 'contact_info'
  get 'contact_info/edit' => 'contact_infos#edit', :as => 'edit_contact_info'
  put 'contact_info/edit' => 'contact_infos#update'
  post 'contact_info/edit' => 'contact_infos#update'

  resources :ourworks

  resources :opinions

  resources :member_teams

  get 'home/landing'

  root 'home#landing'

  resources :product_types do
    resources :product_categories
    resources :product_sub_types
    resources :products do
      resources :product_pictures
    end
  end

  get 'signup'  => 'users#new'

  get 'login'  => 'sessions#new'

  post 'login' => 'sessions#create'

  delete 'logout' => 'sessions#destroy'

  resources :users

  get '/preview' => 'website/site#home', as: 'preview'

  get '/preview/product_type/:id' => 'website/site#product_type', as: 'preview_product_type'

  get '/preview/product_types' => 'website/site#product_type_index', as: 'preview_product_type_index'
  get '/preview/product_types/:product_type_id/products' => 'website/site#products_index', as: 'preview_products_index'
  get '/preview/product_types/:product_type_id/products/:id' => 'website/site#product_show', as: 'preview_product_show'
  get '/info/products/:id' => 'website/site#product_show', as: 'preview_product_info'
  get '/info/ourworks' => 'website/site#ourworks_index', as: 'preview_ourworks_index'

end

app/models/contact_info.rb
class ContactInfo < ActiveRecord::Base

  belongs_to :picture

end

app/models/general_information.rb
class GeneralInformation < ActiveRecord::Base
  self.table_name = 'general_information'

  mount_uploader :catalog, FileUploader
end

app/models/home_website_config.rb
class HomeWebsiteConfig < ActiveRecord::Base

  belongs_to :horizontal_picture, :class_name => 'Picture'
  belongs_to :vertical_picture, :class_name => 'Picture'

end

app/models/member_team.rb
class MemberTeam < ActiveRecord::Base

  belongs_to :picture

end

app/models/opinion.rb
class Opinion < ActiveRecord::Base
end

app/models/ourwork.rb
class Ourwork < ActiveRecord::Base
  belongs_to :picture
end

app/models/picture.rb
class Picture < ActiveRecord::Base
  mount_uploader :photo, PictureUploader
end

app/models/product.rb
class Product < ActiveRecord::Base

  belongs_to :picture

  belongs_to :product_type

  validates :name, :uniqueness =>  true, :presence => true

end

app/models/product_category.rb
class ProductCategory < ActiveRecord::Base
  belongs_to :product_type
  has_many :product_category_product_sub_types, :dependent => :delete_all
end

app/models/product_picture.rb
class ProductPicture < ActiveRecord::Base

  belongs_to :picture

  belongs_to :product

end

app/models/product_sub_type.rb
class ProductSubType < ActiveRecord::Base
  belongs_to :product_type
  has_many :product_category_product_sub_types, :dependent => :delete_all
  validates :name, :uniqueness =>  true, :presence => true
end

app/models/product_type.rb
class ProductType < ActiveRecord::Base

  belongs_to :picture

  validates :name, presence: true
  validates :order, :uniqueness =>  true, :presence => true

end

app/models/ribbon.rb
class Ribbon < ActiveRecord::Base
  belongs_to :picture
end

app/models/social_network.rb
class SocialNetwork < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base

  has_secure_password

  validates :first_name, :uniqueness =>  false, :presence => true

  validates :user_name, :uniqueness =>  true, :presence => true

  validates :last_name, :uniqueness =>  false, :presence => true

end

app/controllers/products_controller.rb
class ProductsController < SecurityController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  before_action :set_product_type

  # GET /products
  # GET /products.json
  def index

      query_by_name = params[:q].to_s

      @products = Product.all.paginate(:page => params[:page], :per_page => 10)

      if query_by_name.size > 0

        @products.where('name LIKE ?' , "%#{query_by_name}%")

      end

  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
    @product_sub_types = ProductSubType.where(product_type_id: @product_type.id).order(:name)
  end

  # GET /products/1/edit
  def edit
    @product_sub_types = ProductSubType.where(product_type_id: @product_type.id).order(:name)
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    @product.product_type_id = @product_type.id
    respond_to do |format|
      if @product.save

        unless params[:product][:image].nil?

          p = Picture.new(photo: params[:product][:image])

          p.save!

          @product.picture = p

          @product.save

        end

        if @product.to_quote

          @product.price = 0

          @product.save!

        end

        format.html { redirect_to @product_type, notice: 'El producto ha sido creado correctamente' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    @product.product_type_id = @product_type.id

    respond_to do |format|

      if @product.update(product_params)

        unless params[:product][:image].nil?

          unless @product.picture.nil?

            @product.picture.remove_photo!

            @product.picture.save!

            @product.picture.update(photo: params[:product][:image])

            @product.picture.save!

          else

            p = Picture.new(photo: params[:product][:image])

            p.save!

            @product.picture = p

            @product.save!

          end

        end

        if @product.to_quote

          @product.price = 0

          @product.save!

        end

        format.html { redirect_to @product_type, notice: 'El producto ha sido actualizado correctamente' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy

    p = @product.picture

    p.remove_photo!

    @product.destroy

    p.destroy!

    respond_to do |format|
      format.html { redirect_to @product_type, notice: 'El producto ha sido eliminado correctamente' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    def set_product_type
      @product_type = ProductType.find(params[:product_type_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :description_detail, :price, :enabled, :product_type_id,
                                      :url_video_youtube, :classification, :sub_type_id, :to_quote)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/opinions_helper.rb
module OpinionsHelper
end

app/helpers/ourworks_helper.rb
module OurworksHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/ribbons_helper.rb
module RibbonsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/products/_form.html.erb
<%= form_for([@product_type,@product], html: {novalidate:'novalidate', class: 'form_validation'}) do |f| %>

    <div class="row clearfix">
      <div class="col-sm-12">
        <div class="form-group">
          <div class="form-line">
            <%= f.text_field :name,
                             class: 'form-control',
                             placeholder: 'Nombre',
                             required: '',
                             :'aria-required'=>'true',
                             :'aria-invalid'=>'true',
                             autocomplete: false,
                             maxlength:'100',
                             minlength:'5'
            %>
          </div>
        </div>
      </div>
    </div>

    <div class="row clearfix">
      <div class="col-sm-12">
        <div class="form-group">
          <div class="form-line">
            <%= f.text_area :description,
                            class: 'form-control',
                            placeholder: 'Descripción'
            %>
          </div>
        </div>
      </div>
    </div>

    <div class="row clearfix">
      <div class="col-sm-12">
        <div class="form-group">
          <div class="form-line">
            <%= f.text_area :description_detail,
                            class: 'form-control editor',
                            id: 'editor',
                            placeholder: 'Descripción'
            %>
          </div>
        </div>
      </div>
    </div>

    <div class="row clearfix">
      <div class="col-sm-12">
        <div class="form-group">
          <div class="form-line">
            <%= f.number_field :price,
                               class: 'form-control',
                               placeholder: 'Precio',
                               required: '',
                               :'aria-required'=>'true',
                               min: 0
            %>
          </div>
        </div>
      </div>
    </div>

    <div class="row clearfix">
      <div class="col-sm-12">
        <div class="form-group">
          <%= f.check_box :to_quote%>
          <label for="product_to_quote">A cotizar</label>
        </div>
      </div>
    </div>

    <div class="row clearfix">
      <div class="col-sm-12">
        <div class="form-group">
          <div class="form-line">
            <%= f.text_field :url_video_youtube,
                             class: 'form-control',
                             type: 'url',
                             placeholder: 'Url Video YouTuBe'
            %>
          </div>
        </div>
      </div>
    </div>

    <div class="row clearfix">
      <div class="col-sm-12">
        <div class="form-group">
          <div class="form-line">
            <%= f.select(
                    :classification,
                    options_for_select(
                        [['Producto', 'product'], ['Accesorio', 'accessory'],['Respuesto', 'replacement']],
                        @product.classification
                    )
                ) %>
          </div>
        </div>
      </div>
    </div>

    <div class="row clearfix">
      <div class="col-sm-12">
        <div class="form-group">
          <div class="form-line">
            <%= f.select(
                :sub_type_id,
                options_for_select(
                    ProductSubType.where(:product_type_id => @product_type.id).collect {|p| [ p.name, p.id ] }.to_a.prepend( [' - Sin Sub Tipo - ', ''] ),
                    @product.sub_type_id
                )
            ) %>
          </div>
        </div>
      </div>
    </div>

    <div class="row clearfix">
      <div class="col-sm-12">
        <div class="form-group">

          <% unless @product.picture.nil?  %>
              <%= image_tag @product.picture.photo_url, style: 'width: 100%; max-width: 300px; height: auto;' %>
          <% end %>
          <div class="form-line input-group">

            <%= f.file_field :image, class:'file', style:'display:none' %>

            <span class="input-group-btn">
                    <button class="browse btn btn-primary" type="button">
                      <i class="material-icons">insert_photo</i>
                    </button>
                </span>
            <input type="text" class="form-control" disabled placeholder="Seleccione un imágen" value="<%= (@product.picture.nil? ? '' : @product.picture.photo_identifier ) %>">
          </div>
        </div>
      </div>
    </div>

    <div class="row clearfix">
      <div class="col-sm-12">
        <div class="form-group">
          <%= f.check_box :enabled%>
          <label for="product_enabled">Habilitado</label>
        </div>
      </div>
    </div>



    <div class="row">
      <div class="col-xs-6 col-sm-4">
        <button type="submit" class="btn btn-primary m-t-15 waves-effect btn-block teal">Guardar</button>
      </div>
      <div class="col-xs-6 col-sm-4">
        <%= link_to 'Atrás', @product_type, class: 'btn btn-default m-t-15 waves-effect btn-block' %>
      </div>
    </div>
<% end %>

app/views/products/edit.html.erb
<div class="block-header">
  <ol class="breadcrumb breadcrumb-col-teal">
    <li>
      <a href="/">
        <i class="material-icons">home</i>
      </a>
    </li>
    <li>
      <%= link_to 'Tipo de Productos', product_types_path %>
    </li>
    <li>
      <%= link_to @product_type.name, @product_type %>
    </li>
    <li class="active">Editar</li>
  </ol>
  <h1>
    Productos
  </h1>
</div>
<!-- Input -->
<div class="row clearfix">
  <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
    <div class="card">
      <div class="header">
        <h2>Editar Producto</h2>
      </div>
      <div class="body">
        <%= render 'form' %>
      </div>
    </div>
  </div>
</div>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Products</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Price</th>
      <th>Enabled</th>
      <th>Product type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.description %></td>
        <td><%= product.price %></td>
        <td><%= product.enabled %></td>
        <td><%= product.product_type_id %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<div class="block-header">
  <ol class="breadcrumb breadcrumb-col-teal">
    <li>
      <a href="/">
        <i class="material-icons">home</i>
      </a>
    </li>
    <li>
      <%= link_to 'Tipo de Productos', product_types_path %>
    </li>
    <li>
      <%= link_to @product_type.name, @product_type %>
    </li>
    <li class="active">Crear</li>
  </ol>
  <h1>
    Productos
  </h1>
</div>
<!-- Input -->
<div class="row clearfix">
  <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
    <div class="card">
      <div class="header">
        <h2>Crear Producto</h2>
      </div>
      <div class="body">
        <%= render 'form' %>
      </div>
    </div>
  </div>
</div>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<p>
  <strong>Enabled:</strong>
  <%= @product.enabled %>
</p>

<p>
  <strong>Product type:</strong>
  <%= @product.product_type_id %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>